name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: AliNaveed01
          THEME: github_dark  # Options: github_light, radical, tokyonight, solarized_dark etc.
